---
build:
  nodes:
    analysis:
      # disable inferred commands
      # as we're only use the code quality analyser
      project_setup:
        override:
          - true
      dependencies:
        override:
          - true
      tests:
        override:
          - js-scrutinizer-run
